[icons]
# font awesome
firefox = ""
Alacritty = ""
Thunderbird = ""
Gpick = ""
Nautilus = "📘"
# smile emoji
MyNiceProgram = "😛"

[aliases]
TelegramDesktop = "Telegram"
"Org\\.gnome\\.Nautilus" = "Nautilus"
"Gimp-\\d\\.\\d\\d" = "Gimp"
"Microsoft Teams - Preview" = "Teams"
"org.jabref.gui.JabRef*" = "JabRef"
"Minecraft*" = "Minecraft"
"libreoffice-*" = "LibreOffice"

[general]
separator = " | "
# default_icon = "" # ""
wm_property = "class"

[options]
remove_duplicates = false
no_names = false
no_icon_names = true
