[theme]
name = "gruvbox-dark"
[theme.overrides]
# idle_bg = "#282828"
# idle_fg = "#A89984"
# info_bg = "#D79921"
# info_fg = "#282828"
# good_bg = "#689D6A"
# good_fg = "#282828"
# warning_bg = "#B16286"
# warning_fg = "#282828"
# critical_bg = "#CC241D"
# critical_fg = "#282828"
# separator = ""
# separator_bg = "auto"
# separator_fg = "auto"
alternating_tint_bg = "#282828"
alternating_tint_fg = "#282828"

[icons]
name = "awesome"

# [[block]]
# block = "github"
# format = "\uf09b {total}"

# [[block]]
# block = "music"
# player = "spotify"
# # dynamic_width = true
# # buttons = ["play", "next"]
# # format = "{artist}  {title}"
# on_collapsed_click = "spotify"

# [[block]]
# block = "net"
# format = "{ssid}: {signal_strength} {speed_down;K*b} {graph_down:4;M*_b#250} {speed_up;K*b} {graph_up:4;M*_b#50}"
# on_click = "nm-connection-editor"

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
ap_format = "{ssid}: {strength}"
device_format = "{icon}{ap}"
primary_only = true

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
# unit = "GB"
interval = 20
warning = 70.0
alert = 80.0
format = "root: {used}/{total} ({available} free)"
on_click = "alacritty -e ranger /"

[[block]]
block = "disk_space"
path = "/home"
info_type = "used"
# unit = "GB"
interval = 20
warning = 75.0
alert = 85.0
format = "home: {used}/{total} ({available} free)"
on_click = "alacritty -e ranger $HOME"

[[block]]
block = "memory"
display_type = "memory"
warning_mem = 75
critical_mem = 85
format_mem = "{mem_used}/{mem_total} ({mem_used_percents} )"
format_swap = "{swap_used}/{swap_total} ({swap_used_percents})"
on_click = "alacritty -e btm"

[[block]]
block = "cpu"
info = 35
warning = 65
critical = 85
format = "{boost} {utilization} {barchart} {frequency}"
on_click = "alacritty -e btm"
[block.theme_overrides]
info_bg = "#60B067"
info_fg = "#131620"

[[block]]
block = "temperature"
collapsed = false
chip = "*-isa-*"
on_click = "alacritty -e btm"

# [[block]]
# block = "load"
# interval = 5

[[block]]
block = "sound"
format = "{output_description} - {volume}"
on_click = "alacritty -e pulsemixer"

[[block]]
block = "pacman"
format = "{pacman} + {aur}"
aur_command = "paru -Qua"
warning_updates_regex = "(linux)"
# critical_updates_regex = "(linux)"
on_click = "alacritty"
[block.theme_overrides]
idle_bg = "#60B067"
idle_fg = "#131620"

[[block]]
block = "uptime"
on_click = "$HOME/.config/rofi/powermenu/type-5/powermenu.sh"

[[block]]
block = "time"
interval = 1
format = "%a %d-%m-%C %T"
